name: Build StockKernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        repository: binhvo7794/kernel_spes_asending
        path: kernel_xiaomi_sm6225
        ref: spes-upstream

    - name: Checkout zipper
      uses: actions/checkout@v4
      with:
        repository: binhvo7794/AnyKernel3
        path: AnyKernel3
        ref: spes

    - name: Android kernel build
      uses: binhvo7794/android-kernel-actions@master
      id: build
      env:
        NAME: StockKernel
        KERNEL_PATH: kernel_xiaomi_sm6225
        ZIPPER_PATH: AnyKernel3
        PYTHON_VERSION: 2
      with:
        arch: arm64
        compiler: aosp-clang/android13-release/clang-r450784d
        defconfig: vendor/spes-perf_defconfig
        image: Image.gz dtbo.img

    - name: Release build
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: Stock Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
          document: ${{ steps.build.outputs.outfile }}
